title: David Heath
author: David Heath
email: heath.davidanthony@gmail.com
description: PhD Research Student in MPC and Programming Languages

baseurl: ""
url: ""
github_username: daheath

theme: minima
github: [metadata]
markdown: kramdown
gems:
  - jekyll-feed
  - minima
