title: Heathblog
email: heath.davidanthony@gmail.com
description: An exploration of program safety.

baseurl: ""
url: ""
github_username: daheath

github: [metadata]
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - minima
