title: David Heath
author: David Heath
email: heath.davidanthony@gmail.com
description: PhD Student in MPC and Programming Languages

baseurl: ""
url: ""
github_username: daheath

theme: jekyll-theme-minimal
github: [metadata]
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
  - jekyll-feed
  - minima
